name: Pre-commit checks
on:
  pull_request:

jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: github-ubuntu-latest-s
    steps:
      - uses: SonarSource/gh-action_pre-commit@ea734ef4ee748f680f3b4ac268c1ba90e245effc # 1.2.1
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        with:
          extra-args: >
            --from-ref=origin/$BASE_REF
            --to-ref=$HEAD_SHA
