---
# yamllint disable rule:truthy
name: Test action
on:
  pull_request:
    paths:
      - .github/workflows/test.yaml
      - action.yaml


jobs:

  vault-action:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: exec vault-action
        id: actual
        uses: ./
        with:
          url: https://vault.staging.sonar.build:8200
          secrets: |
            development/github/token/{REPO_OWNER_NAME_DASH}-ro token | github_ro;
      - name: validate
        shell: bash
        env:
          GITHUB_TOKEN: ${{ fromJSON(steps.actual.outputs.vault).github_ro }}
        run: |
          gh workflow list --all | grep "Test action"
          exit $?
