---
# yamllint disable rule:truthy
name: Test action
on:
  pull_request:
    paths:
      - .github/workflows/test.yaml
      - action.yaml


jobs:

  vault-action:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: exec vault-action
        id: actual
        uses: ./
        with:
          url: https://vault.staging.sonar.build:8200
          secrets: |
            development/github/token/{REPO_OWNER_NAME_DASH}-ro token | github_ro;
            development/github/token/{REPO_OWNER_NAME_DASH}-ro org_name | org_name;
      - name: validate token
        shell: bash
        env:
          GITHUB_TOKEN: ${{ fromJSON(steps.actual.outputs.vault).github_ro }}
        run: |
          gh workflow list --all | grep "Test action"
      - name: validate org_name
        shell: bash
        run: |
          [[ "${{ fromJSON(steps.actual.outputs.vault).org_name }}" = "SonarSource" ]]
